window.PORTFOLIO_CONTENT = {
  en: {
    name: 'Nikita', title: 'Nikita — Bots, APIs & Automation',
    description: 'Nikita builds Telegram bots, data scrapers, API integrations and practical automation. Explore working demos with real outputs.',
    keywords: 'Telegram bots, Python, web scraping, API integrations, Excel, CSV, Google Sheets, PDF, automation',
    skip: 'Skip to content', home: 'Nikita — home', navigation: 'Main navigation', language: 'Language', menu: 'Menu', openMenu: 'Open menu', closeMenu: 'Close menu',
    navServices: 'Services', navProjects: 'Projects', navProcess: 'How I work', navContact: 'Contact',
    heroTitle: ' — Bots, APIs & Automation', heroLead: 'I build Telegram bots, connect business tools and turn repetitive tasks into automated workflows.',
    viewProjects: 'Explore projects', exploreServices: 'What I can build', heroNote: 'From a Telegram request to a structured spreadsheet. From a PDF to usable data.',
    servicesTitle: 'Practical tools for everyday work', servicesIntro: 'A focused script, an integration or a small app — built around the task you need to solve.',
    service1Title: 'Telegram bots', service1Text: 'Collect requests, guide users through a form and prepare structured data for follow-up.',
    service2Title: 'Scrapers & data collection', service2Text: 'Extract information from agreed sources, clean the results and export useful tables.',
    service3Title: 'APIs & workflow automation', service3Text: 'Connect tools, move data between services and automate repeatable steps.',
    service4Title: 'Excel, CSV & Google Sheets', service4Text: 'Clean and structure spreadsheets, prepare exports and connect a Google Sheets workflow to your tools.',
    service5Title: 'PDF processing', service5Text: 'Extract fields from text-based PDFs and flag incomplete records for review.',
    service6Title: 'Small web apps & improvements', service6Text: 'Build focused interfaces for scripts and data tools, or improve an existing website.',
    projectsTitle: 'See the work in action', projectsIntro: 'Concrete tasks, implemented features and visible outputs. Demo projects use test data and are labelled explicitly.',
    task: 'Task', built: 'Built', result: 'Result', technologies: 'Technologies', demo: 'Demo project', localProject: 'Local project', screenshot: 'Open full screenshot',
    processTitle: 'A clear path from task to tool', processIntro: 'Agree on the input, the expected output and a small, testable scope.',
    process1Title: 'Understand the task', process1Text: 'Review the workflow, example files, integrations and any access constraints.',
    process2Title: 'Define the deliverable', process2Text: 'Agree on features, output formats and acceptance checks before implementation.',
    process3Title: 'Build & review', process3Text: 'Show a working version on test data and check normal and error cases together.',
    process4Title: 'Hand over', process4Text: 'Provide the agreed code, setup instructions and a walkthrough of the result.',
    contactTitle: 'Have a workflow in mind?', contactIntro: 'A short description, a sample input and the result you expect are a useful starting point.',
    contactChannel: 'Work Telegram', contactPending: 'Contact details will be added here soon. This page does not accept requests yet.', contactReady: 'Tell me what you would like to automate.', telegramAction: 'Message on Telegram',
    footerText: 'Bots. Data. Less repetitive work.', backTop: 'Back to top ↑'
  },
  ru: {
    name: 'Никита Александрович', title: 'Никита Александрович — боты, API и автоматизация',
    description: 'Никита Александрович: Telegram-боты, парсеры, API-интеграции и автоматизация. Рабочие демопроекты с реальными результатами обработки.',
    keywords: 'Telegram-боты, Python, парсинг, API-интеграции, Excel, CSV, Google Sheets, PDF, автоматизация',
    skip: 'Перейти к содержимому', home: 'Никита — на главную', navigation: 'Основное меню', language: 'Язык', menu: 'Меню', openMenu: 'Открыть меню', closeMenu: 'Закрыть меню',
    navServices: 'Услуги', navProjects: 'Проекты', navProcess: 'Как я работаю', navContact: 'Контакты',
    heroTitle: ' — боты, API и автоматизация', heroLead: 'Создаю Telegram-ботов, связываю рабочие инструменты и превращаю повторяющиеся задачи в автоматические процессы.',
    viewProjects: 'Смотреть проекты', exploreServices: 'Чем могу помочь', heroNote: 'От заявки в Telegram до строки в таблице. От PDF до данных, с которыми можно работать.',
    servicesTitle: 'Инструменты для повседневных задач', servicesIntro: 'Скрипт, интеграция или небольшое приложение — под конкретную задачу вашего процесса.',
    service1Title: 'Telegram-боты', service1Text: 'Сбор заявок, пошаговые формы и подготовка структурированных данных для дальнейшей работы.',
    service2Title: 'Парсеры и сбор данных', service2Text: 'Сбор информации из согласованных источников, очистка результатов и выгрузка в удобные таблицы.',
    service3Title: 'API и автоматизация процессов', service3Text: 'Интеграция инструментов, обмен данными между сервисами и автоматизация повторяющихся действий.',
    service4Title: 'Excel, CSV и Google Sheets', service4Text: 'Очистка и структурирование таблиц, подготовка выгрузок и интеграция Google Sheets с вашими инструментами.',
    service5Title: 'Обработка PDF', service5Text: 'Извлечение полей из текстовых PDF и выделение неполных записей для ручной проверки.',
    service6Title: 'Небольшие веб-приложения', service6Text: 'Понятные интерфейсы для скриптов и работы с данными, а также доработки существующих сайтов.',
    projectsTitle: 'Примеры работающих решений', projectsIntro: 'Конкретные задачи, реализованные функции и видимые результаты. Демопроекты используют тестовые данные и отмечены отдельно.',
    task: 'Задача', built: 'Реализация', result: 'Результат', technologies: 'Технологии', demo: 'Демонстрационный проект', localProject: 'Локальный проект', screenshot: 'Открыть скриншот целиком',
    processTitle: 'От задачи до рабочего инструмента', processIntro: 'Согласуем входные данные, ожидаемый результат и объём работы, который можно проверить.',
    process1Title: 'Разобраться в задаче', process1Text: 'Обсудим процесс, примеры файлов, интеграции и ограничения доступа.',
    process2Title: 'Согласовать результат', process2Text: 'Определим функции, форматы выгрузки и критерии приёмки до начала разработки.',
    process3Title: 'Собрать и проверить', process3Text: 'Покажу рабочую версию на тестовых данных. Вместе проверим обычные сценарии и ошибки.',
    process4Title: 'Передать решение', process4Text: 'Передам согласованный код, инструкцию по запуску и объясню, как пользоваться результатом.',
    contactTitle: 'Есть задача для автоматизации?', contactIntro: 'Для начала пригодятся короткое описание, пример входных данных и ожидаемый результат.',
    contactChannel: 'Рабочий Telegram', contactPending: 'Контакт скоро появится здесь. Пока эта страница не принимает заявки.', contactReady: 'Расскажите, что хотели бы автоматизировать.', telegramAction: 'Написать в Telegram',
    footerText: 'Боты. Данные. Меньше рутины.', backTop: 'Наверх ↑'
  }
};
