// Descriptions are limited to inspected source code and the included demo outputs.
// Image captions distinguish application screenshots from execution reports.
window.PORTFOLIO_PROJECTS = [
  {
    id: 'telegram-leads', type: 'demo', image: 'assets/telegram-execution-report.png', width: 1265, height: 726,
    tech: ['Python', 'aiogram', 'SQLite', 'pytest'],
    links: [{url: 'assets/telegram-output-demo.html', en: 'Execution report', ru: 'Отчёт запуска'}, {url: 'assets/telegram-demo-result.json', en: 'Sample JSON', ru: 'Пример JSON', download: true}],
    en: {title: 'Telegram lead collection bot', summary: 'A guided request flow with validation and structured storage.', task: 'Collect a name, contact, requested service and message without losing the request.', built: 'A step-by-step aiogram flow, validation, confirmation and editing, SQLite storage and an admin notification formatter.', result: 'The local backend run saved a fictional request. Repeating confirmation returned the same record: two submissions, one stored lead. No Telegram messages were sent.', alt: 'Actual Python execution report showing a fictional lead saved in SQLite and a generated notification preview.', caption: 'Execution report from the original Python code on fictional data, not the Telegram interface. The web simulator needs a separate fix.'},
    ru: {title: 'Telegram-бот для сбора заявок', summary: 'Пошаговая заявка с проверкой полей и сохранением в базе.', task: 'Собрать имя, контакт, услугу и сообщение, сохранив заявку для дальнейшей работы.', built: 'Диалог на aiogram, валидация, подтверждение и редактирование, хранение в SQLite и подготовка уведомления администратору.', result: 'Локальный запуск ядра сохранил вымышленную заявку. Повторное подтверждение вернуло ту же запись: две отправки, одна заявка в базе. Сообщения в Telegram не отправлялись.', alt: 'Отчёт выполнения Python: вымышленная заявка в SQLite и подготовленный текст уведомления.', caption: 'Отчёт реального запуска исходного Python-кода на тестовых данных, а не интерфейс Telegram. Веб-симулятор требует отдельного исправления.'}
  },
  {
    id: 'scraper-excel', type: 'demo', image: 'assets/scraper-execution-report.png', width: 1265, height: 810,
    tech: ['Python', 'Beautiful Soup', 'pandas', 'openpyxl'],
    links: [{url: 'assets/scraper-output-demo.html', en: 'Execution report', ru: 'Отчёт запуска'}, {url: 'assets/books.xlsx', en: 'Sample Excel', ru: 'Пример Excel', download: true}, {url: 'assets/books.csv', en: 'Sample CSV', ru: 'Пример CSV', download: true}],
    en: {title: 'Web scraper → Excel & CSV', summary: 'From source HTML to clean, reviewable tables.', task: 'Collect product records and produce a structured spreadsheet.', built: 'HTML parsing, price and text normalization, duplicate removal, visible missing fields and Excel/CSV exports.', result: 'An offline fixture run parsed six records, skipped one invalid record and removed two duplicates. Three cleaned records were exported; the files are available below.', alt: 'Report of a real fixture run with six parsed records and three exported rows.', caption: 'A browser view of the actual execution report and CSV output. Source records are fictional local test data.'},
    ru: {title: 'Парсер данных → Excel и CSV', summary: 'От HTML-страницы до очищенной таблицы для проверки.', task: 'Собрать записи о товарах и подготовить структурированную выгрузку.', built: 'Разбор HTML, нормализация цен и текста, удаление дубликатов, обозначение пропусков и экспорт в Excel/CSV.', result: 'Локальный тестовый запуск разобрал шесть записей, пропустил одну некорректную и удалил два дубликата. В выгрузке — три очищенные записи; файлы доступны ниже.', alt: 'Отчёт реального тестового запуска: шесть разобранных записей и три строки выгрузки.', caption: 'Снимок браузера с фактическим отчётом выполнения и содержимым CSV. Исходные записи — вымышленные тестовые данные.'}
  },
  {
    id: 'pdf-invoices', type: 'demo', image: 'assets/pdf-invoices-results.png', width: 1280, height: 720,
    tech: ['Python', 'pdfplumber', 'Decimal', 'Streamlit', 'openpyxl'],
    links: [{url: 'assets/invoices.xlsx', en: 'Sample Excel', ru: 'Пример Excel', download: true}, {url: 'assets/invoice_usd_valid.pdf', en: 'Input PDF', ru: 'Исходный PDF'}, {url: 'assets/pdf-validation-results.png', en: 'Validation screenshot', ru: 'Скриншот проверки'}],
    en: {title: 'PDF invoice data extractor', summary: 'Turn text-based invoices into tables with validation flags.', task: 'Extract invoice fields and line items for spreadsheet review.', built: 'PDF text extraction, decimal arithmetic, field and total checks, duplicate detection, a Streamlit interface and Excel/CSV export.', result: 'The demo processed five synthetic PDFs: five extracted invoices, three documents with warnings, one duplicate and no extraction errors. It supports the supplied text layouts, not OCR or arbitrary invoice formats.', alt: 'Real Streamlit results with extracted invoices and line items from fictional PDF invoices.', caption: 'Actual Streamlit screenshot after processing synthetic invoices. Company names and invoice data are fictional.'},
    ru: {title: 'Извлечение данных из PDF-счетов', summary: 'Текстовые счета превращаются в таблицы с отметками для проверки.', task: 'Извлечь реквизиты и позиции счетов для работы в таблице.', built: 'Чтение текста PDF, точные десятичные вычисления, проверки полей и сумм, поиск дубликатов, интерфейс Streamlit и экспорт Excel/CSV.', result: 'Демо обработало пять синтетических PDF: пять извлечённых счетов, три документа с предупреждениями, один дубликат и ни одной ошибки извлечения. Поддерживаются подготовленные текстовые шаблоны; OCR и произвольные форматы не заявляются.', alt: 'Реальный экран Streamlit с реквизитами и позициями вымышленных PDF-счетов.', caption: 'Настоящий скриншот Streamlit после обработки синтетических счетов. Названия компаний и данные вымышлены.'}
  },
  {
    id: 'incident-triage', type: 'demo', image: 'assets/incident-triage.png', width: 1280, height: 720,
    tech: ['Python', 'Streamlit', 'Pydantic', 'SQLite'],
    links: [{url: 'assets/incident-approval.png', en: 'Approval workflow', ru: 'Подтверждение оператором'}, {url: 'assets/incident-audit.png', en: 'Audit log', ru: 'Журнал действий'}],
    en: {title: 'Incident triage assistant', summary: 'Structured incident data, a clear decision and a human in the loop.', task: 'Turn incident data into a triage decision an operator can review.', built: 'Rule-based severity, routing and SLA checks, a fallback summary, human approval and a SQLite audit log.', result: 'A Streamlit demo with fictional incidents and a recorded approval workflow. The displayed version runs in fallback mode without external AI calls.', alt: 'Streamlit incident triage demo showing a fictional incident and rule-based severity, routing and SLA.', caption: 'A real screenshot of the safe demo. The fallback notice is visible; no external AI service is called.'},
    ru: {title: 'Помощник разбора инцидентов', summary: 'Данные инцидента, понятное решение и контроль оператора.', task: 'Преобразовать данные инцидента в решение, которое может проверить оператор.', built: 'Определение критичности, маршрута и SLA по правилам, резервное резюме, подтверждение оператором и журнал SQLite.', result: 'Демонстрация Streamlit с вымышленными инцидентами и записью подтверждений. Показанная версия работает в резервном режиме без внешних запросов к ИИ.', alt: 'Демо Streamlit: вымышленный инцидент, критичность, маршрут и SLA, определённые по правилам.', caption: 'Настоящий скриншот безопасной демоверсии. На экране указано, что внешние ИИ-сервисы не вызываются.'}
  },
  {
    id: 'keil-build', type: 'localProject', report: {
      en: 'SUCCESSFUL (5):\n\n  test_dev_; Descriptor3;\n  Dev_324_; Folder_1;\n  Dev_1; Folder_2;\n  TestDevice1; Test1;\n  TestDevice2; Test2;\n\nWITH WARNINGS (0):\n\nERRORS or FATAL (0):',
      ru: 'УСПЕШНО (5):\n\n  test_dev_; Descriptor3;\n  Dev_324_; Folder_1;\n  Dev_1; Folder_2;\n  TestDevice1; Test1;\n  TestDevice2; Test2;\n\nС ПРЕДУПРЕЖДЕНИЯМИ (0):\n\nОШИБКИ или FATAL (0):'
    },
    tech: ['Python', 'Keil UV4', 'subprocess', 'pathlib'],
    links: [{url: 'assets/keil-build-report.txt', en: 'Original saved report', ru: 'Исходный сохранённый отчёт', download: true}],
    en: {title: 'Keil build automation', summary: 'Batch firmware builds with organized outputs and a result report.', task: 'Build descriptor variants and separate successful outputs from warnings.', built: 'A Python script that updates descriptors, invokes Keil UV4, reads device names and sorts binary outputs into result folders.', result: 'The saved report lists five test variants with zero warnings and errors. The report is an existing artifact; firmware compilation was not rerun for this portfolio.', caption: 'English translation of the saved report; the Russian original is available below. This is recorded output, not a live build.'},
    ru: {title: 'Автоматизация сборки Keil', summary: 'Пакетная сборка прошивок с сортировкой файлов и отчётом.', task: 'Собрать варианты дескрипторов и отделить успешные результаты от предупреждений.', built: 'Python-скрипт меняет дескрипторы, вызывает Keil UV4, читает имена устройств и раскладывает бинарные файлы по папкам результатов.', result: 'В сохранённом отчёте — пять тестовых вариантов без предупреждений и ошибок. Это существующий артефакт; компиляция прошивок для портфолио повторно не запускалась.', caption: 'Дословное содержимое сохранённого отчёта с тестовыми именами. Это зафиксированный результат, а не текущая сборка.'}
  }
];
